# Dealing with Data Spring 2020 â€“ Class 4

---

# Iterations and 'While' statements

We've spent some time going into detail about some of the data types and structures available in python. It's now time to talk about how to navigate through some of this data, and use data to make decisions. 

Traversing over data and making decisions based upon data are a common aspect of every programming language. To understand how to do this, we will study the concept of _iteration_. 

Iterations allow us to execute the same task multiple times, and is a key programming concept.

In [0]:
import time # we will use this for the 'time.sleep' function, which we will address soon

# 'While' statements

The `while` statement provides a general way for creating iterative code execution. 

As in the case of the `if` statement, the `while` statement uses a boolean expression that controls the flow of execution. 

The difference is that, when we use the `if` statement, the nested code in executed only once; when we use the `while` statement, the nested code keeps executing, as long as the boolean expression is `True`.

For example, the following example counts until `var` becomes larger than 5

![Flowchart for a while loop (from "How to Think Like a Computer Scientist")](http://interactivepython.org/courselib/static/thinkcspy/_images/while_flow.png)

1. Evaluate the condition, yielding `False` or `True`.
2. If the condition is `False`, exit the `while` statement and continue execution at the next statement that is after the body of the while.
3. If the condition is `True`, execute each of the statements in the body and then go back to step 1.

The body consists of all of the statements below the header with the same indentation.



This type of flow is called a **loop** because the third step loops back around to the top. Notice that if the condition is `False` the first time through the loop, the statements inside the loop are never executed.

In [0]:
import time

variable = 0

while variable <= 5:
  print(variable)
  time.sleep(5.0)    #stop for 5 seconds
  variable += 1

0
1
2
3
4
5

# Example: Tea Cooling

Consider the following example: 

Your tea starts at 115 degrees Fahrenheit. You want it at 110 degrees, and you know that a chip of ice lowers the temperature one degree every second. 

You test the temperature each second, and also print out the temperature before reducing the temperature. In Python you could write and run the code below:

In [0]:
import time
temperature = 115

while temperature > 110:
  
  temperature -= 1
  if temperature % 5 != 0:
    #print("not divisible by 5")
    continue
  time.sleep(.5)
  print(temperature)

115
114
113
112
111
tea is ready

---

## Finite and Infinite Loops

Notice that the body of the loop should change the value of one or more variables so that eventually the condition becomes `False` and the loop terminates. If the condition never becomes False, the loop will repeat forever. Such type of a loop is called an **infinite loop**.

---

# Exercise 1:



The following code contains an infinite loop. 

```python 
n = 10
answer = 1
while n > 0:
    answer = answer + n
    n = n + 1
print(answer)
```

Which is the best explanation for why the loop does not terminate?

1. `n` starts at 10 and is incremented by 1 each time through the loop, so it will always be positive
2. `answer` starts at 1 and is incremented by `n` each time, so it will always be positive
3. You cannot compare `n` to 0 in `while` loop. You must compare it to another variable.
4. In the `while` loop body, we must set `n` to `False`, and this code does not do that.

# Solution

---

# `Break` and `Continue`

Let's discuss now two commands, `break` and `continue`, that allow us to control better the execution of code within a loop.

These two statements are used to modify iteration of loops. `break` is used to *exit immediately* the *inner most _loop_* in which it appears. In contrast, `continue` stops the code executing within the loop and goes on to the *next iteration of the same loop*.

---

For example, consider our example with the bank account. The loop will keep running for ever, if you never withdraw more money than what you have. 

To avoid this infinite loop, we can add an extra check in the code, checking if the year is above a certain limit, and stop execution of the loop at that point.

In [0]:
money_in_bank = 1000
interest = 2
year = 2017
withdrawal_per_period = 50

while money_in_bank > 0:
  print(f"at the beginning of {year} you had ${money_in_bank:.2f} in the bank")      #adding an f tells python to format.
  money_in_bank -= withdrawal_per_period
  money_in_bank = money_in_bank * (1 + interest / 100)
  year += 1
  if year > 2117:
    print("......")
    break

at the beginning of 2017 you had $1000.00 in the bank
at the beginning of 2018 you had $969.00 in the bank
at the beginning of 2019 you had $937.38 in the bank
at the beginning of 2020 you had $905.13 in the bank
at the beginning of 2021 you had $872.23 in the bank
at the beginning of 2022 you had $838.67 in the bank
at the beginning of 2023 you had $804.45 in the bank
at the beginning of 2024 you had $769.54 in the bank
at the beginning of 2025 you had $733.93 in the bank
at the beginning of 2026 you had $697.61 in the bank
at the beginning of 2027 you had $660.56 in the bank
at the beginning of 2028 you had $622.77 in the bank
at the beginning of 2029 you had $584.23 in the bank
at the beginning of 2030 you had $544.91 in the bank
at the beginning of 2031 you had $504.81 in the bank
at the beginning of 2032 you had $463.90 in the bank
at the beginning of 2033 you had $422.18 in the bank
at the beginning of 2034 you had $379.63 in the bank
at the beginning of 2035 you had $336.22 in the bank
at the beginning of 2036 you had $291.94 in the bank
at the beginning of 2037 you had $246.78 in the bank
at the beginning of 2038 you had $200.72 in the bank
at the beginning of 2039 you had $153.73 in the bank
at the beginning of 2040 you had $105.81 in the bank
at the beginning of 2041 you had $56.92 in the bank
at the beginning of 2042 you had $7.06 in the bank

Here is another example, this time with the `continue` command. In the example below, we modify our "tea cooling" example to print the temperature only when temperature is exactly divisible by 5. If not, we use the `continue` command to skip executing the rest of the loop.

---

# Exercise 2

Write a program that receives user input for three pieces of information:

* a starting balance, 
* a target balance, 
* and an interest rate (entered as 0.05 for 5%, for example)

The program should then outputs the number of years required for the starting balance to have grown larger than the target balance. While this can be computed directly mathematically, we want for this exercise to use a while loop to figure out the answer. 

The answer should just be a line stating something like: "To grow an initial investment of \\$1000 to  \\$2000 at 5.0% will require `XX` years".

_Hint: You will need a variable to store the number of years that passed. You will also need a variable to hold the current balance in the account, as it grows over the years._

In [0]:
starting = 1000
target = 2000
interest = 0.05
year = 0
# your code here
while starting < target:
  starting = starting * (1 + interest)
  year += 1

  if starting < 1000:
    break
print(f"To grow an initial investment of \$1000 to \$2000 at 5.0% will require {year} years")

To grow an initial investment of \$1000 to \$2000 at 5.0% will require 15 years

# Solution

---

# For Loops

* similar to `while`, `for` empowers us to execute the same code block several times
* unlike `while`, `for` does not use a conditional, rather it uses an **iterator** that has a start/end <br>
<br>
* Syntax
```python
for iteration_variable in iterator:
       execute_code_block
```

For example, imagine we want to remind students of an assignment deadline:

In [0]:
names_list = ["Bill","Sara", "Peter","Vic","Hannah"]

for name in names_list:
  print("Hi,", name)

Hi, Bill
Hi, Sara
Hi, Peter
Hi, Vic
Hi, Hannah

* The `name` variable is called the **loop variable** or **iteration variable** 
* The `name` variable **changes** with each iteration of the loop. 
* The `name` variable iteratively takes the value of each of the six values in the `students` list.
* Each loop iteration, Python checks to see if more items can be processed. 
    * If none left we've reached the **terminating condition of the loop** and the loop ends.
        * The program execution continues at the next statement after the loop's code block.
     * If items are left, the loop variable now points to the next item in the list.

![Flowchart for a for loop (from "How to Think Like a Computer Scientist")](http://interactivepython.org/courselib/static/thinkcspy/_images/new_flowchart_for.png)

---

# Exercise 3


Write a program that uses a for loop to print

* `One of the months of the year is January`
* `One of the months of the year is February`
* `One of the months of the year is March`
* etc ...

In [0]:
months = ['January', 'February', 'March', 'April', 'May', 'June', 
          'July', 'August', 'September', 'October', 'November', 'December']
for i in months:
  print(f"One of the months of the year is {i}")
# your code here

One of the months of the year is January
One of the months of the year is February
One of the months of the year is March
One of the months of the year is April
One of the months of the year is May
One of the months of the year is June
One of the months of the year is July
One of the months of the year is August
One of the months of the year is September
One of the months of the year is October
One of the months of the year is November
One of the months of the year is December

# Solution

---

# Exercise 4

Assume you have a list of numbers `12, 10, 32, 3, 66, 17, 42, 99, 20`

* Write a loop that prints each of the numbers on a new line.
* Write a loop that prints each number and its square on a new line.

In [0]:
numbers = [12, 10, 32, 3, 66, 17, 42, 99, 20]
for i in numbers:
  print(i, i * i)
# your code here

12 144
10 100
32 1024
3 9
66 4356
17 289
42 1764
99 9801
20 400

# Solution

---

# Ranges of Integers

* A common pattern in programming is to use `for` to iterate through a range of integers

* `range` is a a convenient Python function for this purpose that generates a list of numbers <br>
<br>
* Syntax
```python
range(end_integer_exclusive)
range(start_integer,end_integer_exclusive)
range(start_integer,end_integer_exclusive,step_value)
```

In [0]:
for i in range(4):
  print(i)

0
1
2
3

In [1]:
for i in range(4,10):
  print(i)
  print(type(i))

4
<class 'int'>
5
<class 'int'>
6
<class 'int'>
7
<class 'int'>
8
<class 'int'>
9
<class 'int'>

In [0]:
for i in range(4,8,2):
  print(i)

4
6

# Warning

You might be inclined to write code like this:

In [0]:
names = ["Bill","Sara", "Peter","Vic","Hannah"]
for i in range(0,len(names)):
  print(names[i])

Bill
Sara
Peter
Vic
Hannah

...instead of...

In [0]:
for i in names:
  print(i)

Bill
Sara
Peter
Vic
Hannah

When in Python, take advantage of Pythonic style. It's easier to read and maintain!

---

# Iterating Through Lists, Sets, and Dictionaries

The process of iterating through sets and tuples is pretty much identical to the one for lists. Let's see a few examples.

In [0]:
set_a = {1,2,3,4,5,6}

In [0]:
tuple_a = {1,2,3,4,5,6}
for i in tuple_a:
  print(i)

1
2
3
4
5
6

# Iterating over dictionaries

With dictionaries, iteration can happen through keys, values, or both.

In [0]:
phones = {
    
    "Panos": "212-998-0803",
    "Maria": "656-233-5555",
    "John": "693-232-5776",
    "Jake": "415-794-3423"
}

# Iterating over keys

By default, when we iterate over a dictionary, we are iterating over the keys.

In [0]:
for i in phones:
  print("key = ", i)

key =  Panos
key =  Maria
key =  John
key =  Jake

# Iterating over values

It is also possible to iterate over the values for the dictionary:

In [0]:
for i in phones:
  print("key = ", i, "value = ", phones[i])

key =  Panos value =  212-998-0803
key =  Maria value =  656-233-5555
key =  John value =  693-232-5776
key =  Jake value =  415-794-3423

# Iterating over key-value pairs

We use `dict.items()` to return an iterator of the dictionary's key-value pairs as tuples

In [0]:
for i in phones.items:
  print(i)

('Panos', '212-998-0803')
('Maria', '656-233-5555')
('John', '693-232-5776')
('Jake', '415-794-3423')

---

# Exercise 5

You are given the composite data structure below:

In [0]:
data = {
        "Foster": {
            "Job": "Professor", 
            "YOB": 1965, 
            "Children": ["Hannah"],
            "Awards": ["Best Teacher 2014", "Best Researcher 2015"],
            "Salary": 120000
        }, 
        "Joe": {
            "Job": "Data Scientist", 
            "YOB": 1981,
            "Salary": 200000
        },
        "Maria": { 
            "Job": "Software Engineer", 
            "YOB": 1993, 
            "Children": [],
            "Awards": ["Dean's List 2013", "Valedictorian 2011", "First place in Math Olympiad 2010"]
        }, 
        "Panos": { 
            "Job": "Professor", 
            "YOB": 1976, 
            "Children": ["Gregory", "Anna"]
        },
    }

# Question 1:

* Print the names of the people from the dictionary below, by iterating through the keys

In [0]:
# print the names of people in the data

for names in data:
  print(names)

Foster
Joe
Maria
Panos

# Question 2:

* Print the age of each person, by iterating through the keys, and then looking up the "YOB" entry.

In [0]:
# print the names and age

for names in data:
  print(data[names]["YOB"])

1965
1981
1993
1976

In [0]:
for values in data.values():
  print(values["YOB"])

1965
1981
1993
1976

# Question 3:

* Print the names of people born after 1980

In [0]:
# print the names of people born after 1980

for names in data:
  if data[names]["YOB"] > 1980:
    print(names)

Joe
Maria

# Question 4:

* Print the number of children for each person. You need to check if the "Children" list exists in the dictionary.

In [0]:
# print the number of children for each person

for names in data:
  if "Children" in data[names]:
    print(len(data[names]["Children"]))

1
0
2

In [0]:
for values in data.values():
  if "Children" in values:
    print(values["Children"])

['Hannah']
[]
['Gregory', 'Anna']

---

# Common Loop Patterns: Finding an Element in the List

We have the list of NBA teams, and we want to find the team that plays in _Brooklyn_. We will start by creating a `looking_for` variable for storing the value of `Brooklyn`.

Then we will use the loop to to through the list of teams, to find whether any of the team names contains the `looking_for` string. 

We will also use a special data type `None` - a value that represents no value. (For folks familiar with NULL - it's the same idea.)

In [0]:
nba_teams = [
    "Atlanta Hawks", "Boston Celtics", "Brooklyn Nets", "Charlotte Hornets",
    "Chicago Bulls", "Cleveland Cavaliers", "Dallas Mavericks",
    "Denver Nuggets", "Detroit Pistons", "Golden State Warriors",
    "Houston Rockets", "Indiana Pacers", "LA Clippers", "Los Angeles Lakers",
    "Memphis Grizzlies", "Miami Heat", "Milwaukee Bucks",
    "Minnesota Timberwolves", "New Orleans Pelicans", "New York Knicks",
    "Oklahoma City Thunder", "Orlando Magic", "Philadelphia 76ers",
    "Phoenix Suns", "Portland Trail Blazers", "Sacramento Kings",
    "San Antonio Spurs", "Toronto Raptors", "Utah Jazz", "Washington Wizards"
]

looking_for = "Brooklyn"
result = None
for team in nba_teams:
  if looking_for in team:
    result = team 
    print(result)

Brooklyn Nets

In [0]:
if "Brooklyn Nets" in nba_teams:
  print(1)

1

# Creating a new list

This time, instead of just printing out the results, we will store the franchise names in a new list, and then print each on a new line.

In [0]:
nba_teams = [
    "Atlanta Hawks", "Boston Celtics", "Brooklyn Nets", "Charlotte Hornets",
    "Chicago Bulls", "Cleveland Cavaliers", "Dallas Mavericks",
    "Denver Nuggets", "Detroit Pistons", "Golden State Warriors",
    "Houston Rockets", "Indiana Pacers", "LA Clippers", "Los Angeles Lakers",
    "Memphis Grizzlies", "Miami Heat", "Milwaukee Bucks",
    "Minnesota Timberwolves", "New Orleans Pelicans", "New York Knicks",
    "Oklahoma City Thunder", "Orlando Magic", "Philadelphia 76ers",
    "Phoenix Suns", "Portland Trail Blazers", "Sacramento Kings",
    "San Antonio Spurs", "Toronto Raptors", "Utah Jazz", "Washington Wizards"
]
teams2 = []


for team in nba_teams:
  teams2.append(team.split(" ")[0])

teams2

['Atlanta',
 'Boston',
 'Brooklyn',
 'Charlotte',
 'Chicago',
 'Cleveland',
 'Dallas',
 'Denver',
 'Detroit',
 'Golden',
 'Houston',
 'Indiana',
 'LA',
 'Los',
 'Memphis',
 'Miami',
 'Milwaukee',
 'Minnesota',
 'New',
 'New',
 'Oklahoma',
 'Orlando',
 'Philadelphia',
 'Phoenix',
 'Portland',
 'Sacramento',
 'San',
 'Toronto',
 'Utah',
 'Washington']

---

In [0]:
if "a" in "abc":
  print("1")

1

# Functions

In programming, functions assign a name to a block of code, and allow us to execute a more complex set of instructions, without having to replicate the code and the corresponding logic over and over.

Python provides a set of functions that already built-in. You are already familiar with some functions:

# `len`, `sum`, `max`, and `min`

You have already encountered `len`, `sum`, `max`, and `min`.

In [0]:
numbers = [1,2,5,3,2,5]

In [0]:
min(numbers)

1

Note that every function has **input** and **output**. In all the examples above, the input is a list of numbers (`numbers`).

What is the output?
* For `len()`, the output is a number corresponding to the length of the list.
* For `max()` the output is a number corresponding to the maximum element of the list.
* For `min()` the output is a number corresponding to the minimum element of the list.
* For `sum()` the output is a number corresponding to the sum of all the elements in the list.

The concept of input and output is very important: In a sense this is what a function does: Takes as input one or more values, and returns back an output. What happens inside the function is something that we do not need to worry about; we can treat the function as a black box.

# `round`

At its simplest form, rounds gets one input: a number. It returns an integer as the output, which is the integer closest to the input number (aka "rounded" number)

In [0]:
round(4.55)

5

The `round()` function can also take two inputs. The first input is the number, and the second input is the number of decimal digits that we want to keep.

Notice the concept: Round accepts as input one or two values, and returns back as output a number. **Input** and **output**, focus on this part.

# `sorted`

Consider now the `sorted` function. This function takes as **input** as list, and returns as **output** the sorted version of the list.

Notice that the function is not limited to retuning just a number. It may return *a list* of numbers. (In fact, it may return a string, or pretty much anything.)

Notice also that we do not need to know *how* the function goes from input to output. We put as input an unsorted list, and get back a sorted one. We do not know what sorting technique was used. We only get back the result. This abstraction allow us to write more readable programs, by writing code at a higher level, without having to replicate all the details.

---

# Functions from Libraries

We can also add more functions by `import`-ing libraries. The Python 3 standard library list is here: https://docs.python.org/3/library/

Python developers worldwide have developed many popular libraries, available at the Python Package Index: https://pypi.org/

# `math` functions

 A common example is the `math` library.

In [0]:
import math

In [0]:
math.sqrt(3)

1.7320508075688772

As we mentioned before, this function has an input (`x`) and an output (`y`), which is the square root of x. Again, we do not care how the square root is calculated, we only get back the outcome.

Here is another example, where we use the `math.gcd` function to find the _greatest common divisor_ of two numbers, `x` and `y`. (This is the largest number that divides exactly both `x` and `y`.) 

In this case, the function gets as input two numbers, x and y, and returns an integer as a result. And again, we do not need to know _how_ the function is computing the greatest common divisor, we just get back the result.

---

# Exercise 6

Use the `math.sqrt` function to get the square root of the numbers:
* 121
* 12321
* 1234321
* 123454321

In [0]:
# your code here

# Solution

---

# `random` functions

Another commonly used library is the `random` library that returns random numbers.

In [0]:
import random

For example, the function `random.random()` will return back a random value from 0 to 1, which will be different every time.

In [0]:
random.random()

0.7720755804378024

In [0]:
names = ["alex", "mara", "max"]
random.choice(names)

'mara'

So, `random.random()` is a type of function that gets *zero*  inputs, and returns back an integer as the output.

Here is another function `random.choice(t)` that accepts as input a list of values, and picks one of them at random.

---

# Exercise 7

* Create a list of 8 random integer numbers. (Hint: You can multiply `random.random()` by 100, and then use `round()` to get numbers between 0 and 100.)

In [0]:
# your code here

# Solution

---

# User-Defined Functions

We will now learn how to write our own functions. Why?

Because as programs become more complex, they start involving more and more steps. At some point, the code becomes very long, and it becomes difficult to understand what is going on. It is the equivalent of having a book without chapters, sections, or any form of structure. In fact, long code that is not using functions is often called "spaghetti code", because it is long and messy.

So, once you start writing your code using functions, your program will start reading like a sequence of high-level steps, making your code much more readable. There are many other advantages, but at first, you will notice readability as the first key benefit.

# Creating User Defined Functions

To define a function in Python, we need the following:
* Function definition in Python start with the `def` keyword
* After `def` we put the name of the function
* After the name of the function we put an opening parenthesis,  and
* Inside the parentheses the names of zero or more input variables, separated by commas, followed by a closing parethesis, and
* After the closing parentheses we have a colon `:`
* Then we put a block of code with the actions for the function.
* At the end of the function code, we have a `return` statement, followed by the output of the function

Let's see a few examples

# Example 1: Square a number

We want to write a function that takes as input a number $x$ and returns back its square $x^2$. We will call the function `square`. So we write:

In [0]:
def square(x):
    result = x*x
    return result

So, let's dissect the example above:

* We start with the `def` keyword
* After def we put the name of the function `square`
* After the name of the function, `square` we have a pair of parentheses, with one input variable `x` inside
* After the closing parentheses we have a colon `:`
* Then we have our code that computes the square of x (`result = x*x`)
* And at the end of the function code, we have a `return` statement that returns back the `result`

Notice that nothing happens once you execute the cell above. To use the function, you need to call it. For example:

In [0]:
square(4)

16

_Note: If you try to execute the cell that use the function `square` but you have not executed the cell that contains the function definition, then you will get an error. In order to use a function, you first need to define it, and execute the corresponding code._

In [0]:
# now what happens if we execute square("abc")?

# Exception Handling
* Programs are sticklers - they follow the rules
* But that means, they're rigid
* Exception handling enables you to build agility into your functions and programs
* Python provides the `try` and `except` statements for exception handling
* Put your "sensitive" code in the `try` block
    * Python will "test run" that block - if it works without errors - GREAT!
    * Otherwise, if there are errors, Python will run the code in the `except` block
* Syntax:
```python
    try:
        code_block
    except:
        alternate_code_block
```

In [0]:
def square(x):
  try:
    result = x*x
    return result
  except:
    print("it only accept numeric input")

square("sss")

it only accept numeric input

## Example 2: From pounds to kilograms

We want to write a function that converts weight from pounds to kilograms. The conversion is 1 pound = 0.453592 Kilograms.

For example: Weight of 155 lbs is 70.30676 Kg

Let's see first how we would write this as straightforward code, without a function:

And to avoid having a magic number, we may want to assign 0.453592 to a variable:

Now, let's convert this into a function. We will call it `pounds_to_kg`.

So lets see also what are the inputs and outputs: In this case it is simple, we have the weight in pounds as input, and we get as output the weight in kilograms.

And now that we have defined our function, we can use it:

Notice one thing: The `kg_in_lb = 0.453592` variable does not appear outside the function anymore. This is a simple example of abstraction: We do not need to care how the conversion happens, or what the calculation is anymore. We can simply use the function.

Of course, in this example it is trivial, but as our code becomes more and more complex, hiding the details becomes more and more important

---

# Warning: Common mistake, `print` instead of `return`

Now, let's examine a common mistake. The code below takes the initial code, and fits it in a function.

What is the critical difference? The function above uses a `print` statement instead of a `return`. 

This is a very common mistake for beginners. It also takes a lot of time to overcome this, because the code "works", as we can see below.

However, see what happens if we change the code, and try to store the result of the function in a variable.

Notice that the variable `weight_kgs` has the valune `None`. This happened because the function did not generate any output. **Printing is NOT a function output**. Only the `return` keyword generate the output for the function.

---

# Example 3: Meal with tip and tax

Now let's revisit our example from the earlier sessions in the class: Compute the total cost of a meal. 

Suppose that we buy food for \$30. We also need to pay the tax on top (which is 8.875\% in NY), and put a tip, say 15\%, on the pre-tax amount. The code for doing this calculation:

In [0]:
food = 30
tax = 8.875/100
tip = 15/100
cost = food + food * tax + food * tip

print(f"The cost of the meal will be: ${cost}")

Now let's define a function called `meal_cost`. What are the inputs and outputs in this case?

* Inputs: food cost, tax, tip
* Output: Total cost

Now, let's start making some changes. Say that we want to enter the tax as a percentage, and not as a small decimal. So we would like to have `tax = 8.875` instead of `tax = 8.875/100`. Similarly for the tip. We also want the cost to be rounded to two decimals

# Example 4: Get the length of a text in words

We will now write a non-math oriented function. We want a function that takes as input a piece of text, and returns the number of words in it. What is the length of the article in words? For simplicity we assume that words are separated by spaces.

In [0]:
article = """One person was believed to be missing after an oil rig storage platform exploded Sunday night on Lake Pontchartrain, just north and west of New Orleans. Seven people were taken to hospitals after the explosion, and three of them remained in critical condition Monday morning, Mike Guillot, the director of emergency medical services at East Jefferson General Hospital, said at a news conference. The other four were released. Sheriff Joe Lopinto of Jefferson Parish said at the news conference, We are fairly confident there is an eighth person, adding that search efforts were continuing, and the Coast Guard had contacted the family of the person. No fatalities had been reported as of Monday morning. The blast occurred shortly after seven pm near St Charles Parish and the city of Kenner. The platform is in unincorporated Jefferson Parish. Officials are still investigating the cause of the explosion, but the City of Kenner said on its Facebook page that authorities on the scene report that cleaning chemicals ignited on the surface of the oil rig platform."""
print(article)

So, in this case, we have the input being the string variable that contains the text, and the output is a number.

---

# Exercise 8: Check if a number is within a range


Write a function `in_range` that checks if a number `n` is within a given range `(a ... b)` (inclusive on both ends) and returns `True` or `False`. The function takes `n`, `a`, and `b` as parameters.

In [0]:
# your code here

# Solution

---

# Exercise 9: Remove duplicate entries from a list, and sort

Write a `dedup` function that takes as input a list and returns back another list, with only unique elements and sorted. For example, if the input is `[1,2,5,5,5,3,3,3,3,4,5]` the returned list should be `[1, 2, 3, 4, 5]`. If the input is `['New York', 'New York',  'Paris', 'London', 'Paris']` the returned list should be `['London', 'New York', 'Paris']`.

In [0]:
def dedup(input_list):
    ... #your code here

In [0]:
# running the code below should return [1, 2, 3, 4, 5]

in_list = [1,2,5,5,5,3,3,3,3,4,5]
dedup(in_list)

In [0]:
# running the code below should return ['London', 'New York', 'Paris']

in_list = ['New York', 'New York',  'Paris', 'London', 'Paris']
dedup(in_list)

# Solution

---